---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tekton-hub-ui
spec:
  to:
    kind: Service
    name: tekton-hub-ui
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
