name: golangci-lint
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:  # yamllint disable-line rule:empty-values
    branches:
      - main 

permissions:
  contents: read
  checks: write  # Used to annotate code in the PR

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.x"

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/.cache/pip
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Check out code
      uses: actions/checkout@v4

    - uses: alexellis/setup-arkade@v3
    - uses: alexellis/arkade-get@master
      with:
        golangci-lint: v1.64.8

    - name: Lint API code
      run: |
        make api-lint

